#!/bin/bash

# The MIT License
#
# Copyright 2023 Jerald Vanderraad | jerald@members.fsf.org
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# -------------------------------------------------------------------------------------
# METACAT, a simple bash script to organize a FLAC collection by metatdata tags.
# It would work well as a nightly cronjob.
#
# Requirements: The flac package which includes metaflac for reading metadata
# This script expects a consistently and properly tagged FLAC collection!
#
# You will need to set the following: LINKBASE, SORTBY, TARGETS
# -------------------------------------------------------------------------------------

if [ ! type metaflac ];
	then echo Error: metacat requires flac to be installed.. && exit 1
	else [
		echo metaflac found.. proceeding ]
		fi

shopt -s nullglob dotglob

# Base directory where folders / symlinks will be created 
LINKBASE=/media/FLAC.ext3


# what tags are we sorting by? 
declare -a SORTBY
SORTBY=(ARTIST GENRE)

for TAG in ${SORTBY[@]}
	do mkdir -p $LINKBASE/BY_$TAG
	# Clean old symlinks out...
	find $LINKBASE/BY_$TAG/ -exec rm -rfv {} \;
	# Define target directories to index, space separated. Be sure to include trailing asterisk
		declare -a TARGETS
		TARGETS=("/media/mylib1/*" "/media/mylib2/*")
		for LIBRARY in ${TARGETS[@]}
			do for dir in "${LIBRARY[@]}"
				do declare -a FILES
			FILES=$(find "$dir" -type f -name \*.flac | head -1)
			ATT=`metaflac --show-tag=$TAG "${FILES[0]}" | sed -e "s/$TAG=//i"`
				# maybe various artists
				if [ "$TAG" = 'ARTIST' ];
					then
					if [[ -n `metaflac --show-tag=ALBUMARTIST "${FILES[0]}"` ]];
				then
				ATT=`metaflac --show-tag=ALBUMARTIST "${FILES[0]}" | sed -e "s/ALBUMARTIST=//i"`
			fi
		fi
		LINKDIR="$LINKBASE/BY_$TAG/$ATT"
		mkdir -pv "$LINKDIR"
		ln -sv "$dir" "$LINKDIR"/
	done
     done
done
